import { useState, type ReactNode } from 'react';
import { motion } from 'framer-motion';
import QRCode from 'react-qr-code';

import {
  ArrowDownTrayIcon,
  LockClosedIcon,
  DocumentTextIcon,
  PhotoIcon,
  Battery50Icon,
  SignalIcon,
  FingerPrintIcon,
  RadioIcon,
  FireIcon,
  CloudIcon,
  MapPinIcon,
  UserIcon,
  ClockIcon,
  ChevronRightIcon,
} from '@heroicons/react/24/outline';

import type { Evidence } from '@/types';
import { useApp } from '@/context/AppContext';
import { Badge, severityTone, stageTone } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { fmtTime, fmtDate } from '@/lib/format';

const STAGE_FLOW = [
  'Collected',
  'Logged',
  'Reviewed',
  'Archived',
] as const;

export function EvidenceCard({
  evidence,
}: {
  evidence: Evidence;
}) {
  const [showQR, setShowQR] = useState(false);

  const currentStage = evidence.stage || 'Collected';
  const [isAdvancing, setIsAdvancing] = useState(false);

  const { advanceStage, isReadOnly } = useApp();

  const archived = currentStage === 'Archived';

  const currentIdx = STAGE_FLOW.indexOf(
    currentStage as (typeof STAGE_FLOW)[number]
  );

  /*
   * ADVANCE STAGE
   */
  const handleAdvanceStage = async () => {
    if (isReadOnly || archived) return;

    const nextIndex = currentIdx + 1;

    if (nextIndex >= STAGE_FLOW.length) return;

    const nextStage = STAGE_FLOW[nextIndex];

    try {
      setIsAdvancing(true);
      await advanceStage(evidence.id, nextStage);
    } catch (error) {
      console.error('Failed to advance evidence stage:', error);
    } finally {
      setIsAdvancing(false);
    }
  };
  const generateHash = async () => {
    console.log("HASH ID BEING SENT:", evidence.evidenceId);

    try {
      const response = await fetch(
        `http://https://detectivex-project-production.up.railway.app/api/evidence/${evidence.evidenceId}/hash`,
        {
          method: "POST",
        }
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.message || "Hash generation failed");
      }

      alert(
        `SHA-256 Hash Generated Successfully!\n\n${data.hash}\n\nIntegrity: ${data.integrityStatus}`
      );
    } catch (error) {
      console.error("Hash generation failed:", error);
      alert("Failed to generate hash. Make sure the backend is running.");
    }
  };
  /*
   * DOWNLOAD CHAIN OF CUSTODY REPORT
   */
  const downloadChainOfCustody = () => {
    const content = `
DETECTIVEX - CHAIN OF CUSTODY REPORT
====================================

Evidence ID: ${evidence.id}
Evidence Type: ${evidence.type}
Description: ${evidence.description}
Officer: ${evidence.officer}
Location: ${evidence.location}
Condition: ${evidence.condition}

CHAIN OF CUSTODY
----------------
1. Collected
2. Logged
3. Reviewed
4. Archived

Current Stage: ${currentStage}
Status: ${evidence.status ?? 'N/A'}

Collected At:
${fmtDate(evidence.timestamp)} ${fmtTime(evidence.timestamp)}

RFID: ${evidence.rfid || 'N/A'}
GPS: ${evidence.gps || 'N/A'}
Temperature: ${evidence.temperature ?? 'N/A'}°C
Humidity: ${evidence.humidity ?? 'N/A'}%
Battery: ${evidence.battery ?? 'N/A'}%
Signal Strength: ${evidence.signal ?? 'N/A'}%
Fingerprint Match: ${evidence.fingerprintMatch ? 'Match' : 'None'
      }

Generated by DetectiveX
Digital Evidence Management System
`;

    const blob = new Blob([content], {
      type: 'text/plain;charset=utf-8',
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');

    link.href = url;
    link.download = `chain-of-custody-${evidence.id}.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setTimeout(() => {
      URL.revokeObjectURL(url);
    }, 1000);
  };

  /*
   * QR CODE DATA
   *
   * Use the complete evidence record so newly-created
   * MongoDB evidence gets its actual information.
   */
  const qrPayload = JSON.stringify({
    id: evidence.id,
    type: evidence.type,
    description: evidence.description,
    location: evidence.location,
    officer: evidence.officer,
    timestamp: evidence.timestamp,
    rfid: evidence.rfid,
    stage: currentStage,
    status: currentStage,
  });

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.9 }}
      className="fx-card fx-border rounded-2xl overflow-hidden shadow-glass"
    >
      {/* HEADER */}
      <div className="p-4 border-b fx-border flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-xl bg-forensic-primary/15 grid place-items-center fx-primary font-mono font-bold text-xs">
            {evidence.id}
          </div>

          <div>
            <p className="text-sm font-semibold fx-text">
              {evidence.type}
            </p>

            <p className="text-[11px] fx-muted font-mono">
              {evidence.rfid || 'NO RFID'}
            </p>
          </div>
        </div>

        <div className="flex gap-1.5">
          <Badge
            tone={severityTone(evidence.severity)}
            className="!text-[10px]"
          >
            {evidence.severity}
          </Badge>

          <Badge
            tone={stageTone(currentStage)}
            className="!text-[10px]"
          >
            {currentStage}
          </Badge>
        </div>
      </div>

      {/* PHOTO */}
      <div className="relative h-44 fx-cardalt overflow-hidden">
        {evidence.photo ? (
          <img
            src={evidence.photo}
            alt={evidence.id}
            className="h-full w-full object-cover"
          />
        ) : (
          <div className="h-full w-full flex flex-col items-center justify-center fx-muted">
            <PhotoIcon className="h-10 w-10 mb-1" />

            <span className="text-xs">
              No photo attached
            </span>
          </div>
        )}

        <div className="absolute bottom-2 left-2 fx-glass fx-border rounded-lg px-2 py-1 text-[10px] font-mono fx-text">
          {evidence.id}
        </div>
      </div>

      {/* DETAILS */}
      <div className="p-4 space-y-3">

        <div className="grid grid-cols-2 gap-3 text-xs">

          <Detail
            icon={<MapPinIcon className="h-3.5 w-3.5" />}
            label="Location"
            value={evidence.location || 'Unknown'}
          />

          <Detail
            icon={<UserIcon className="h-3.5 w-3.5" />}
            label="Officer"
            value={evidence.officer || 'Unknown'}
          />

          <Detail
            icon={<ClockIcon className="h-3.5 w-3.5" />}
            label="Collected"
            value={`${fmtDate(evidence.timestamp)} ${fmtTime(
              evidence.timestamp
            )}`}
          />

          <Detail
            icon={<LockClosedIcon className="h-3.5 w-3.5" />}
            label="Condition"
            value={evidence.condition || 'Unknown'}
          />

        </div>

        {/* DESCRIPTION */}
        <div>
          <p className="text-[10px] fx-muted uppercase tracking-wider mb-1">
            Description
          </p>

          <p className="text-xs fx-text leading-relaxed">
            {evidence.description || 'No description'}
          </p>
        </div>

        {/* NOTES */}
        {evidence.notes && (
          <div>
            <p className="text-[10px] fx-muted uppercase tracking-wider mb-1">
              Notes
            </p>

            <p className="text-xs fx-muted leading-relaxed">
              {evidence.notes}
            </p>
          </div>
        )}

        {/* CHAIN OF CUSTODY */}
        <div className="fx-cardalt fx-border rounded-xl p-3">

          <p className="text-[10px] fx-muted uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
            <ArrowDownTrayIcon className="h-3.5 w-3.5" />
            Chain of Custody
          </p>

          <div className="flex items-center justify-between">

            {STAGE_FLOW.map((stage, i) => {

              const done = i <= currentIdx;
              const active = i === currentIdx;

              return (
                <div
                  key={stage}
                  className="flex items-center flex-1 last:flex-none"
                >

                  <div className="flex flex-col items-center gap-1">

                    <div
                      className={`h-6 w-6 rounded-full grid place-items-center text-[10px] font-bold transition ${done
                        ? 'bg-forensic-primary text-black'
                        : 'fx-border fx-cardalt fx-muted'
                        } ${active
                          ? 'ring-2 ring-forensic-primary/40'
                          : ''
                        }`}
                    >
                      {i + 1}
                    </div>

                    <span
                      className={`text-[9px] ${done ? 'fx-text' : 'fx-muted'
                        } whitespace-nowrap`}
                    >
                      {stage}
                    </span>

                  </div>

                  {i < STAGE_FLOW.length - 1 && (
                    <div
                      className={`h-0.5 flex-1 mx-1 ${i < currentIdx
                        ? 'bg-forensic-primary'
                        : 'fx-border'
                        }`}
                    />
                  )}

                </div>
              );
            })}

          </div>
        </div>

        {/* SENSOR DATA */}
        <div className="fx-cardalt fx-border rounded-xl p-3">

          <p className="text-[10px] fx-muted uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
            <SignalIcon className="h-3.5 w-3.5" />
            Sensor Telemetry
          </p>

          <div className="grid grid-cols-3 gap-2">

            <Sensor
              icon={<MapPinIcon className="h-3 w-3" />}
              label="GPS"
              value={evidence.gps || 'N/A'}
              small
            />

            <Sensor
              icon={<FireIcon className="h-3 w-3" />}
              label="Temp"
              value={`${evidence.temperature ?? 'N/A'}°C`}
            />

            <Sensor
              icon={<CloudIcon className="h-3 w-3" />}
              label="Humidity"
              value={`${evidence.humidity ?? 'N/A'}%`}
            />

            <Sensor
              icon={<FingerPrintIcon className="h-3 w-3" />}
              label="Print"
              value={
                evidence.fingerprintMatch
                  ? 'Match'
                  : 'None'
              }
              tone={
                evidence.fingerprintMatch
                  ? 'text-forensic-success'
                  : 'fx-muted'
              }
            />

            <Sensor
              icon={<RadioIcon className="h-3 w-3" />}
              label="RFID"
              value={evidence.rfid || 'N/A'}
              small
            />

            <Sensor
              icon={<Battery50Icon className="h-3 w-3" />}
              label="Battery"
              value={`${evidence.battery ?? 'N/A'}%`}
              tone={
                evidence.battery < 30
                  ? 'text-forensic-danger'
                  : 'text-forensic-success'
              }
            />

          </div>

          {/* SIGNAL */}
          <div className="mt-2.5">

            <div className="flex justify-between text-[10px] fx-muted mb-1">
              <span>Signal Strength</span>

              <span className="tabular-nums">
                {evidence.signal ?? 0}%
              </span>
            </div>

            <div className="h-1.5 rounded-full fx-border overflow-hidden">

              <div
                className={`h-full rounded-full ${evidence.signal < 30
                  ? 'bg-forensic-danger'
                  : 'bg-forensic-secondary'
                  }`}
                style={{
                  width: `${Math.max(
                    0,
                    Math.min(100, evidence.signal ?? 0)
                  )}%`,
                }}
              />

            </div>

          </div>
        </div>

        {/* ACTIONS */}
        <div className="flex gap-2 pt-1">

          {/* ADVANCE */}
          <Button
            variant="secondary"
            size="sm"
            className="flex-1"
            disabled={isReadOnly || archived || isAdvancing}
            onClick={handleAdvanceStage}
          >
            {archived ? (
              <>
                <LockClosedIcon className="h-4 w-4" />
                Archived
              </>
            ) : (
              <>
                Advance Stage
                <ChevronRightIcon className="h-4 w-4" />
              </>
            )}
          </Button>

          {/* DOWNLOAD */}
          <Button
            variant="ghost"
            size="sm"
            type="button"
            onClick={downloadChainOfCustody}
          >
            <ArrowDownTrayIcon className="h-4 w-4" />
            Download
          </Button>

          {/* GENERATE HASH */}
          <Button
            variant="ghost"
            size="sm"
            type="button"
            onClick={generateHash}
          >
            Generate Hash
          </Button>

          {/* QR */}
          <Button
            variant="ghost"
            size="sm"
            type="button"
            onClick={() => setShowQR((previous) => !previous)}
          >
            <DocumentTextIcon className="h-4 w-4" />

            {showQR ? 'Hide QR' : 'QR'}
          </Button>

        </div>

        {/* QR CODE */}
        {showQR && (
          <motion.div
            initial={{
              opacity: 0,
              height: 0,
            }}
            animate={{
              opacity: 1,
              height: 'auto',
            }}
            className="flex flex-col items-center gap-2 pt-2 border-t fx-border"
          >

            <div className="bg-white p-3 rounded-lg">

              <QRCode
                value={qrPayload}
                size={160}
                level="M"
              />

            </div>

            <p className="text-[10px] fx-muted text-center">
              Scan to verify chain of custody for{' '}
              <span className="font-mono">
                {evidence.id}
              </span>
            </p>

          </motion.div>
        )}

      </div>
    </motion.div>
  );
}

/* ================================
   DETAIL COMPONENT
================================ */

function Detail({
  icon,
  label,
  value,
}: {
  icon: ReactNode;
  label: string;
  value: string;
}) {
  return (
    <div>

      <p className="text-[10px] fx-muted uppercase tracking-wider flex items-center gap-1 mb-0.5">
        {icon}
        {label}
      </p>

      <p className="text-xs fx-text truncate">
        {value}
      </p>

    </div>
  );
}

/* ================================
   SENSOR COMPONENT
================================ */

function Sensor({
  icon,
  label,
  value,
  small,
  tone = 'fx-text',
}: {
  icon: ReactNode;
  label: string;
  value: string;
  small?: boolean;
  tone?: string;
}) {
  return (
    <div className="fx-card fx-border rounded-lg px-2 py-1.5">

      <p className="text-[9px] fx-muted uppercase flex items-center gap-1">
        {icon}
        {label}
      </p>

      <p
        className={`${small ? 'text-[10px]' : 'text-xs'
          } font-medium ${tone} truncate`}
      >
        {value}
      </p>

    </div>
  );
}
